# Generated by Django 2.0 on 2019-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_type',
            name='type_name',
            field=models.CharField(max_length=20),
        ),
    ]
