# Generated by Django 2.0 on 2019-02-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190205_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['screen_time']},
        ),
    ]
